package com.meenu.codingskills.leetcode.easy;

import java.util.HashMap;

/*
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

public class FindTheDifference {

	private char findTheDifference(String s, String t) {
		HashMap<Character, Integer> map = new HashMap<>();
		
		for(char c : s.toCharArray()) {
			map.put(c, map.getOrDefault(c, 0) + 1);
		}
		
		for(char c : t.toCharArray()) {
			if(map.containsKey(c) && map.get(c) == 0 || !map.containsKey(c)) {
				return c;
			}
			map.put(c, map.get(c) - 1);
		}
		return '!';
    }
	
	public void findSolution() {
		String s = "abcd";
		String t = "abcde";
//		String s = "a";
//		String t = "aa";
		
		char diff = findTheDifference(s, t);
		System.out.println("Difference : " + diff);
	}
}
